services:
  flask-backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

  react-frontend:
    build: ./Frontend
    ports:
      - "3000:80"